name: lambda
version: 0.0.0.0

dependencies:
  - base
  - text
  - containers
  - array
  - transformers
  - mtl

default-extensions:
  - NoFieldSelectors

library:
  exposed-modules: Hello
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - lambda
      - tasty
      - tasty-hunit
