name: lambda
version: 0.0.0.0

dependencies:
  - base
  - text
  - containers
  - array
  - vector
  - transformers
  - mtl
  - megaparsec

default-extensions:
  - NoFieldSelectors
  - DuplicateRecordFields

library:
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Main
    source-dirs:
      - test
      - src
    dependencies:
      - tasty
      - tasty-hunit
