name: lambda
version: 0.0.0.0

executables:
  lambda:
    main: Main.hs
    source-dirs:
      - app
      - src
    ghc-options: -Wall

dependencies:
  - base
  - text
  - containers
  - array
  - vector
  - transformers
  - mtl
  - megaparsec 
  - hashable
  - dlist

default-extensions:
  - NoFieldSelectors
  - DuplicateRecordFields

library:
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Main
    source-dirs:
      - test
      - src
    dependencies:
      - tasty
      - tasty-hunit
